channels:
- conda-forge
dependencies:
- python=3.12.5
- pip<=25.1.1
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.0
  - numpy==2.0.2
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - typing==3.7.4.3
name: mlflow-env
